steps:
  # Deploy to Cloud Run using source-based deployment
  # This command will automatically build the container if a Dockerfile is present
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'portal-empleabilidad'
      - '--source'
      - '.'
      - '--region'
      - 'us-central1'
      - '--set-cloudsql-instances'
      - 'portal-empleabilidad-cft:us-central1:empleabilidad-db'
      - '--set-env-vars'
      - 'DB_HOST=/cloudsql/portal-empleabilidad-cft:us-central1:empleabilidad-db,APP_ENV=production,APP_DEBUG=false'
      - '--update-secrets'
      - '/app/secrets/laravel-env=laravel-env:latest'
      - '--allow-unauthenticated'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/sgai-repo/portal-empleabilidad:latest'

options:
  logging: CLOUD_LOGGING_ONLY
