steps:
  # ===============================
  # Build the container image
  # ===============================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA'
      - '-t'
      - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:latest'
      - '.'

  # ===============================
  # Push image (commit SHA)
  # ===============================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA'

  # ===============================
  # Push image (latest)
  # ===============================
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:latest'

  # ===============================
  # Deploy to Cloud Run
  # ===============================
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA'
      - '--region'
      - '${_DEPLOY_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

      # ===============================
      # Cloud SQL
      # ===============================
      - '--set-cloudsql-instances'
      - '${_AR_PROJECT_ID}:${_DEPLOY_REGION}:${_CLOUDSQL_INSTANCE}'

      # ===============================
      # ENV VARIABLES (Laravel + GCS)
      # ===============================
      - '--set-env-vars'
      - >-
        APP_NAME=PortalEmpleabilidad,
        APP_ENV=cloud,
        APP_DEBUG=false,
        APP_URL=${_APP_URL},
        DB_CONNECTION=pgsql,
        DB_HOST=/cloudsql/${_AR_PROJECT_ID}:${_DEPLOY_REGION}:${_CLOUDSQL_INSTANCE},
        DB_PORT=5432,
        CACHE_STORE=database,
        SESSION_DRIVER=database,
        CACHE_CONNECTION=database,
        QUEUE_CONNECTION=sync,
        LOG_CHANNEL=stderr,
        LOG_LEVEL=info,
        FILESYSTEM_DISK=gcs,
        GOOGLE_CLOUD_PROJECT_ID=${_AR_PROJECT_ID},
        GOOGLE_CLOUD_STORAGE_BUCKET=magallanes-portal-files-prod,
        GOOGLE_CLOUD_STORAGE_URL=https://storage.googleapis.com/magallanes-portal-files-prod

      # ===============================
      # SECRETS
      # ===============================
      - '--set-secrets'
      - 'APP_KEY=APP_KEY:latest'
      - '--set-secrets'
      - 'DB_DATABASE=DB_DATABASE:latest'
      - '--set-secrets'
      - 'DB_USERNAME=DB_USERNAME:latest'
      - '--set-secrets'
      - 'DB_PASSWORD=DB_PASSWORD:latest'

# ===============================
# Images built
# ===============================
images:
  - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA'
  - '${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:latest'

# ===============================
# Build options
# ===============================
options:
  logging: CLOUD_LOGGING_ONLY

# ===============================
# Substitution variables
# ===============================
substitutions:
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _AR_PROJECT_ID: portal-empleabilidad-cft
  _AR_REPOSITORY: cloud-run
  _SERVICE_NAME: portal-empleabilidad
  _DEPLOY_REGION: us-central1
  _CLOUDSQL_INSTANCE: empleabilidad-db
  _APP_URL: https://portal-empleabilidad-287614110959.us-central1.run.app
