steps:
  # ===============================
  # Build the container image
  # ===============================
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA"
      - "-t"
      - "${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:latest"
      - "."

  # ===============================
  # Push image (commit SHA)
  # ===============================
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA"

  # ===============================
  # Push image (latest)
  # ===============================
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:latest"

  # ===============================
  # Deploy to Cloud Run
  # ===============================
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA"
      - "--region"
      - "${_DEPLOY_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"

      # ===============================
      # ENV VARIABLES
      # ===============================
      - "--set-env-vars=APP_NAME=PortalEmpleabilidad,APP_ENV=cloud,APP_DEBUG=false,APP_URL=${_APP_URL},DB_CONNECTION=pgsql,DB_HOST=34.31.99.145,DB_PORT=5432,DB_DATABASE=bolsatrabajo,DB_USERNAME=laravel,DB_PASSWORD=Laravel2026!,CACHE_STORE=database,SESSION_DRIVER=database,CACHE_CONNECTION=database,QUEUE_CONNECTION=sync,LOG_CHANNEL=stderr,LOG_LEVEL=info,FILESYSTEM_DISK=gcs,GOOGLE_CLOUD_PROJECT_ID=${_AR_PROJECT_ID},GOOGLE_CLOUD_STORAGE_BUCKET=magallanes-portal-files-prod,GOOGLE_CLOUD_STORAGE_URL=https://storage.googleapis.com/magallanes-portal-files-prod,CLOUDINARY_URL=cloudinary://239386487643389:MbImHVcwpBm3U8cxM9RSa4-X8cI@dnmvoioqg"


      # ===============================
      # APP KEY desde Secret Manager
      # ===============================
      - "--set-secrets"
      - "APP_KEY=APP_KEY:latest"

images:
  - "${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA"
  - "${_AR_HOSTNAME}/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:latest"

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _AR_PROJECT_ID: portal-empleabilidad-cft
  _AR_REPOSITORY: cloud-run
  _SERVICE_NAME: portal-empleabilidad
  _DEPLOY_REGION: us-central1
  _APP_URL: https://portal-empleabilidad-287614110959.us-central1.run.app
